apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - image: barbaralipnik/scraper:latest
          name: scraper
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: scraper
