kumuluzee:
  name: scraper-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/scraperDS
  metrics:
    web-instrumentation:
      - name: scraper-endpoint
        url-pattern: /v1/scraper/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
      <Configuration name="comments">
          <Appenders>
              <Console name="console" target="SYSTEM_OUT">
                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
              </Console>
              <Socket name="logstash" host="c01cd245-8af8-4d32-82dc-b9744260a7e6-ls.logit.io"
              port="15190" protocol="udp">
                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
              </Socket>
          </Appenders>
          <Loggers>
              <!-- Default logger -->
              <Root level="all">
                  <AppenderRef ref="console" level="info" />
                  <AppenderRef ref="logstash" level="trace" />
              </Root>
          </Loggers>
      </Configuration>'
rest-properties:
  maintenance-mode: false
microservice-locations:
  merchants: http://localhost:8081
  emails: http://localhost:8083
